bot:
  TOKEN: !ENV ${BOT_TOKEN}
  mongodb: !ENV ${MONGO_URL}
  
  # These configs are optional
  # prefix: !!python/tuple ["a!", "A!"]
  # description: "Anime Girls bot"
  # activity: "with anime girls"
